export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const COUNTER_INCREASE = 'COUNTER_INCREASE';
export const COUNTER_TOGGLE_VIEW = 'COUNTER_TOGGLE_VIEW';
